### ISSUE TITLE
Heroku domain still Http 

### ISSUE THREAD

**Issue by jmprovencher** [gboudreau/certbot-heroku#4]
Any idea why after running successfully the plugin and having SSL properly installed on the heroku app, Heroku still displays : Your app can be found at http://my.custom.domain.com (without HTTPS). The app is only available via HTTPS if you explicitly enter https://my.custom.domain.com in the browser.

**Comment by gboudreau** [comment]
That's normal; having HTTPS enabled doesn't disable the non-HTTPS custom domain you configured.
I myself had to manually configure my nginx to redirect non-HTTPS requests to my HTTPS URL.

If you need further details, you should contact Heroku support; this is unrelated to how you enabled HTTPS (manually using their web-app, or automatically using this LE plugin).

Cheers.
