### ISSUE TITLE
HOW TO: NodeJS server.

### ISSUE THREAD

**Issue by PunkHaz4rd** [gboudreau/certbot-heroku#5]
Is there a way for you to provide an example of server configuration for NodeJS user ?
Thanks

**Comment by gboudreau** [comment]
I don't do node.js myself, so I wouldn't know. I would guess that would depend on what framework you use to route the incoming HTTP requests...

(Side note: why are you not using Heroku' new [automated certificate management](https://devcenter.heroku.com/articles/automated-certificate-management) feature? It pretty much deprecates this plugin here, except if you're using the free plan.)

**Comment by PunkHaz4rd** [comment]
Oh :/ I didn't know it existed in the first place. Sorry.

**Comment by gboudreau** [comment]
No problem. Still a valid question for users of the free plan.
I added a note about ACM at the top of the README, since ACM is new, and was made available after I published this plugin.

**Comment by EcZachly** [comment]
So I got this working using NodeJS with this route:
`router.get('/.well-known/acme-challenge/:str', function(req, res){
    res.send(process.env.LETS_ENCRYPT_CHALLENGE);
});
`

**Comment by gboudreau** [comment]
Thanks. Committed a sample node.js script that uses that.
