### ISSUE TITLE
Does this still work on the free tier?

### ISSUE THREAD

**Issue by fgblomqvist** [gboudreau/certbot-heroku#7]
As far as I know, manually generating and installing certs does not work on the free tier anymore.
The following error message is displayed:
```
 ▸    You need to be running on either Hobby or Professional dynos to be able to
 ▸    use SNI SSL.
```
Does your plugin still work somehow?

**Comment by gboudreau** [comment]
Indeed, documentation now says:
> Heroku SSL is included for free on any app that uses paid dynos

Ref: https://devcenter.heroku.com/articles/ssl

**Comment by gboudreau** [comment]
Changed README to point this out. Thx for the pointer.

**Comment by fgblomqvist** [comment]
Heads-up: there's a typo in the readme. It says the plug-in is not deprecated instead of now deprecated.

**Comment by gboudreau** [comment]
Thx. Fixed.
